---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: configure-alertmanager-operator-registry
  namespace: openshift-operator-lifecycle-manager
spec:
  image: quay.io/app-sre/configure-alertmanager-operator-registry:staging-latest
  displayName: Configure Alertmanager Operator
  icon:
    base64data: ""
    mediatype: ""
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cluster-monitoring
  namespace: openshift-monitoring
  annotations:
    olm.providedAPIs: Alertmanager.v1.monitoring.coreos.com,Prometheus.v1.monitoring.coreos.com,PrometheusRule.v1.monitoring.coreos.com,ServiceMonitor.v1.monitoring.coreos.com
spec:
  staticProvidedAPIs: true
  selector:
    matchLabels:
      openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  name: configure-alertmanager-operator
  source: configure-alertmanager-operator-registry
  sourceNamespace: openshift-operator-lifecycle-manager
  channel: staging
