---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: configure-alertmanager-operator-registry
  namespace: openshift-operator-lifecycle-manager
spec:
  image: quay.io/app-sre/dedicated-admin-operator-registry:staging-latest
  displayName: Configure Alertmanager Operator
  icon:
    base64data: ""
    mediatype: ""
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  channel: staging
  name: configure-alertmanager-operator
  source: configure-alertmanager-operator-registry
  sourceNamespace: openshift-operator-lifecycle-manager
