---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  name: configure-alertmanager-operator
  source: configure-alertmanager-operator-registry
  sourceNamespace: openshift-operator-lifecycle-manager
  channel: staging
