apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sreconfigs.kni.openshift.io
spec:
  group: kni.openshift.io
  names:
    kind: SREConfig
    listKind: SREConfigList
    plural: sreconfigs
    singular: sreconfig
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
