---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dms-secret
  namespace: openshift-monitoring
data:
  SNITCH_URL: aHR0cHM6Ly9ub3NuY2guaW4vZXg0bXBsM3NuMXRjaElE
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pd-secret
  namespace: openshift-monitoring
data:
  PAGERDUTY_KEY: YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGY=
